-- Create Database
CREATE DATABASE IF NOT EXISTS DEMO_DB;

-- Use Database
USE DATABASE DEMO_DB;

-- Create Schema
CREATE SCHEMA IF NOT EXISTS PUBLIC;

-- Use Schema
USE SCHEMA PUBLIC;

-- Create Customer Table
CREATE OR REPLACE TABLE CUSTOMER (
    CUSTOMER_ID NUMBER(10,0) AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);
